name: QRZ Bio Uploader

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Checkout QRZ_bio_uploader repository
      uses: actions/checkout@v2
      with:
        repository: komppa/QRZ_bio_uploader
        path: QRZ_bio_uploader

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r QRZ_bio_uploader/requirements.txt

    - name: Execute qrz.py script with index.html content
      run: |
        python3 QRZ_bio_uploader/qrz.py ${{ secrets.callsign }} ${{ secrets.password }} "$(cat index.html)"